name: Push commit
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: |
          date
      - name: Commit report
        run: |
          cat report.txt >> README.md
          git config --global user.name 'CI'
          git commit -am "Updating artifact"
          git push
